sudo: false

branches:
    only:
       - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  on:
   branch: master
