sudo: false

branches:
    only:
       - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen -g Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  on:
   branch: master
